### ISSUE TITLE
Argument hints for WordPress functions missing?

### ISSUE THREAD

**Issue by tliebig** [purplefish32/sublime-text-2-wordpress#2]
Dear purplefish,

I was delighted to see a wordpress bundle for sublime text. For some reason, although it autocompletes the function names (get_po... > get_post), but does not hint what arguments are accepted (http://codex.wordpress.org/Template_Tags/get_posts). 

I was hoping I could spare me a couple of visits to the codex by having that information right within sublime text. Any idea what I might be doing wrong (installed the package through the package manager, so I figured that shouldn't a cause of error :o/)

Yours,
Torsten

**Comment by jtsternberg** [comment]
Closing. Please open a new issue if something is still relevant.
