### ISSUE TITLE
<?php is duplicated

### ISSUE THREAD

**Issue by sparkdevelopment** [purplefish32/sublime-text-2-wordpress#36]
The scope for the plugin header snippet is PHP, so I have to add <?php to my file to denote it is PHP, yet the snippet add <?php. Can this be removed if using this method to denote PHP (as opposed to Set Format)?

**Comment by jtsternberg** [comment]
Fixed in https://github.com/purplefish32/sublime-text-2-wordpress/commit/9f9041446e52535bdc603363ebd53030be913b41
