### ISSUE TITLE
Sublime Text 3 Support

### ISSUE THREAD

**Issue by mrwweb** [purplefish32/sublime-text-2-wordpress#37]
I'm not sure what's involved but it would be great to have support for Sublime Text 3. It seems to be very stable and lots of people are using it (since it came out in 2013...)

**Comment by pranksinatra** [comment]
+1

**Comment by abelq** [comment]
+1

**Comment by dangelion** [comment]
+1

(actually this extension doesn't work on ST 3?)

**Comment by rebdev** [comment]
+1

**Comment by vongoh** [comment]
+1

**Comment by demartini** [comment]
+1

**Comment by raua** [comment]
it's still not working for sublime text 3?

**Comment by christophwolff** [comment]
+1

**Comment by braginteractive** [comment]
+1

**Comment by kumaxim** [comment]
+1

**Comment by purplefish32** [comment]
I havent been using either sublime text or wordpress recently, but I am pretty sure it works in ST3

**Comment by jtsternberg** [comment]
It does indeed work with ST3. Are you all seeing it not work, or simply haven't tried it because it has "2" in the name?
