### ISSUE TITLE
Maintainer assistance?

### ISSUE THREAD

**Issue by jtsternberg** [purplefish32/sublime-text-2-wordpress#44]
Thank you for this package, it is awesome.

Right now, you are the top result and used result for WordPress snippets for sublime, but the package is woefully out of date. 

![](http://b.ustin.co/K4g8Ov+)

Are you open to maintainer assistance? I would love to take the time to get the hooks/constants/etc up-to-date with the current version of WordPress.

**Comment by purplefish32** [comment]
Hi there, yeah I had moved away from both WordPress and Sublime Text for a while, the package definitely needs some TLC. A have added you as a collaborator to the project.

**Comment by jtsternberg** [comment]
Awesome, thank you sir!

**Comment by kallookoo** [comment]
Hi, 
Because we not merge my package with this.
I do not see any sense in having two doing the same thing.

**Comment by kallookoo** [comment]
@jtsternberg , what do you think about joining the packages, it absurd that in the repository there is more than one.

The url of my packages: https://github.com/kallookoo/sublime-text-wordpress
and url of my generator: https://github.com/kallookoo/sublime

This is the last attempt to unify our work, if you want to continue offering an outdated package, so be it. :(
It was the main reason why I made another like it.
