### ISSUE TITLE
First Tab –> Select all parameters

### ISSUE THREAD

**Issue by jpp86** [purplefish32/sublime-text-2-wordpress#47]
Hi, I don't know why, but when I press the Tab, it doesn't select all parameters but directly the first parameter.

I use the last version with Sublime Text 3 (3143)

Thanks in advance and sorry for my english :)

**Comment by purplefish32** [comment]
That how it is intended to work
Write the first parameter then push tab again to get to the second
parameter and so on

**Comment by jpp86** [comment]
Thanks for the answer. So there isn't the possibility to delete all the params with a Tab or another key?

For example I want to use category list without passing params, but I obtain the follow and I have to delete all inside the brakets.

get_the_category_list( $separator = '', $parents = '', $post_id = false );

and I want:

get_the_category_list();

Thanks again :)

**Comment by jtsternberg** [comment]
When it selects the first chunk (e.g. `$separator = ''`), just use the built-in Sublime key binding `cmd`+`shift`+`space` to select all inside the parenthesis, and delete.

![select-all-params](https://user-images.githubusercontent.com/1098900/34529525-5250d1dc-f07a-11e7-9656-ed5c94fc804f.gif)

**Comment by jpp86** [comment]
Thanks a lot :)

I found `ctrl` + `shift` + `m` for Windows (Expand selection to brackets).

Sorry for this "not an issue" and thanks again for all.
